server:
  port: ${SERVER_PORT:8888}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appdb}?currentSchema=${DB_SCHEMA:testdb}
    username: ${DB_USER:app}
    password: ${DB_PASSWORD:app1234!}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    create-schemas: true
    schemas: ${DB_SCHEMA:testdb}
    default-schema: ${DB_SCHEMA:testdb}
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: ${JWT_SECRET:change-me-super-secret-key-at-least-32-bytes}
    access-token-minutes: 5
    refresh-token-minutes: 60
  security:
    refresh-cookie-name: REFRESH_TOKEN
    refresh-cookie-path: /api/auth
    refresh-cookie-samesite: Lax
    refresh-cookie-secure: false
  file-storage-path: ${FILE_STORAGE_PATH:C:/storage}

decorator:
  datasource:
    enabled: true
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true  # SQL 자체는 여러 줄로 두고 싶으면 유지
      log-format: "#%(currentTime) | took %(executionTime)ms | %(category) | connection %(connectionId)\n%(sql)"
      tracing:
        include-parameter-values: true