spring:
  mail:
    host: ${MAIL_HOST:email-smtp.ap-northeast-2.amazonaws.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  mail:
    enabled: true
    from: ${MAIL_FROM:noreply@common-system.com}
    base-url: ${APP_BASE_URL}
